language: java
sudo: required
services: docker

env:
  global:
    - secure: WBJI+q1QXLSPhJwHEwgY1dec7dpm7Wdw1vinQa1G6uaoq08yt/+SXRw4ID0QkGzZhcvrNI4/nYzb2b6JS9o5KzE+Yu/8Wp7Gw5LWSRwwj5k1yKt7f2wkvxHkNwUEmwQ2VFIf9WFmtcQsaMomre3hIYuS67i7900ICKm1vNJh4lc=
    - BINTRAY_USER=bozaro

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -f  $HOME/.gradle/caches/*/fileContent/fileContent.lock
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
  - rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
  - rm -f  $HOME/.gradle/caches/journal-*

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - debhelper
    - gnome-doc-utils

jobs:
  include:
    # Different JDKs
    - stage: test
      env: GITLAB_VERSION=11.0.3-ce.0 # Gitlab >= 11.0 no longer has API v3 (issue #176)
      jdk: oraclejdk8
    - stage: test
      env: GITLAB_VERSION=11.0.3-ce.0
      jdk: oraclejdk9
    - stage: test
      env: GITLAB_VERSION=11.0.3-ce.0
      jdk: oraclejdk10
    - stage: test
      env: GITLAB_VERSION=11.0.3-ce.0
      jdk: oraclejdk11

    # Different Gitlabs
    - stage: test
      env: GITLAB_VERSION=10.2.5-ce.0 # Gitlab >= 10.2 no longer has /session endpoint (issue #154)
      jdk: oraclejdk8
    - stage: test
      env: GITLAB_VERSION=9.5.10-ce.0 # Last 9.x build, actually nothing special about it
      jdk: oraclejdk8
    - stage: test
      env: GITLAB_VERSION=9.3.3-ce.0  # We use this in production. Do not forget to update GitLabIntegrationTest.java when changing this
      jdk: oraclejdk8

    - stage: deploy
      jdk: oraclejdk8 # Deploy releases using oldest supported jdk
      script: ./gradlew assembleDist
      before_deploy:
        # Set the packages name and details in the descriptor file
        - sed -i "s/__SUBJECT__/$BINTRAY_USER/g" bintray-descriptor.json
        - sed -i "s/__BINTRAY_REPO__/git-as-svn/g" bintray-descriptor.json
        - sed -i "s/__REPO_SLUG__/${TRAVIS_REPO_SLUG//\//\\/}/g" bintray-descriptor.json
        - sed -i "s/__VERSION__/$TRAVIS_TAG/g" bintray-descriptor.json
      deploy:
        - provider: releases
          api-key:
            secure: DOfUgYJSdDiRIjgULtOxR0jdvkxuXPn+4Q+UGYtnQNiov7hAJ6VbdQpGSczi0ik/RLzf51NuBJm4PuFGVy5sexeJuw4iUEa+gnJlDglJI/UHiHcr+E4HJnTUweAHTiHGADm2qyhyg3+n0D4pZ8m2j86UvNImZWYcPUwup0lul4U=
          file_glob: true
          file:
            - build/distributions/git-as-svn*
          skip_cleanup: true
          on:
            tags: true
            repo: bozaro/git-as-svn
        - provider: pages
          github_token:
            secure: DOfUgYJSdDiRIjgULtOxR0jdvkxuXPn+4Q+UGYtnQNiov7hAJ6VbdQpGSczi0ik/RLzf51NuBJm4PuFGVy5sexeJuw4iUEa+gnJlDglJI/UHiHcr+E4HJnTUweAHTiHGADm2qyhyg3+n0D4pZ8m2j86UvNImZWYcPUwup0lul4U=
          skip_cleanup: true
          local_dir: build/doc
          on:
            branch: master
            repo: bozaro/git-as-svn
        - provider: script
          script: deploy/deploy.debian.sh
          skip_cleanup: true
          on:
            tags: true
            repo: bozaro/git-as-svn
        - provider: bintray
          file: bintray-descriptor.json
          user: $BINTRAY_USER
          key:
            secure: "edL8Fb4WreerduO8bQj4RUwSFp9+UmXnolWm6PdsoMWMm8WNRwlU6gXBf39eZJjMMXkoftwkowcHiwar5YJHyZeIjlhLfvq2SmfmN/jVUCLppd+WrvSpUbm6A+7VShT9doIIcATvmHCC6Rk5kgchwWvPQQunYNy/Q9eRsz4STBk="
          skip_cleanup: true
          on:
            tags: true
            repo: bozaro/git-as-svn
